# Generated by Django 6.0.2 on 2026-02-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='version',
            field=models.CharField(blank=True, max_length=100, verbose_name='Version'),
        ),
    ]
